# Generated by Django 4.0.6 on 2022-11-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_delete_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
