# Generated by Django 4.0.6 on 2022-08-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_historiaclinica_delete_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiaclinica',
            old_name='nombre',
            new_name='paciente',
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='antecedentes',
            field=models.CharField(max_length=900),
        ),
    ]
