# Generated by Django 4.0.6 on 2022-08-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_rename_nombre_historiaclinica_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='estudios',
            field=models.ImageField(upload_to='servicios'),
        ),
    ]
